export default Object.freeze({
  SEEK_URL: "https://www.seek.com.au/",
  KEYWORDS: "#keywords-input",
  LOCATION: "#SearchBar__Where",
  SEARCH: "#searchButton",
  JOB_CONTAINER: "div._1wkzzau0.szurmz0.szurmzb",
  //   JOB_TITLE: "div._365Hwu1 > article:nth-child(INDEX)",
  JOB_TITLE: 'a[data-automation="jobTitle"]',
  JOB_COMPANY: 'a[data-automation="jobCompany"]',
  JOB_DETAILS: 'span[data-automation="jobShortDescription"]',
  JOB_CATEGORY: 'a[data-automation="jobSubClassification"]',
  JOB_LOCATION: 'a[data-automation="jobLocation"]',
  JOB_LISTING_DATE: 'span[data-automation="jobListingDate"]',
  JOB_SALARY: 'span[data-automation="jobSalary"]',
  JOBS_NUM: "#SearchSummary > h1",
});

export const KEYWORDS = [
  "react",
  "javascript",
  "vue",
  ".net",
  "php",
  "java",
  "azure",
  "aws",
  "python",
  "angular",
  "node.js",
  "html",
  "css",
  "typescript",
  "docker",
  "kubernetes",
  "sql",
  "mongodb",
  "git",
  "agile",
  "scrum",
  "devops",
  "aws lambda",
  "aws s3",
  "aws ec2",
  "aws cloudformation",
  "aws dynamodb",
  "aws rds",
  "azure functions",
  "azure storage",
  "azure cosmos db",
  "azure devops",
  "azure sql database",
  "java spring",
  "java hibernate",
  "python django",
  "python flask",
  "react native",
  "angular",
  "angular 2+",
  "typescript",
  "html5",
  "css3",
  "sass",
  "less",
  "webpack",
  "babel",
  "rest api",
  "graphql",
  "microservices",
  "agile",
  "remote",
  "work from home",
];
